# DO NOT CHANGE THIS FILE!
#
# This is run on a non-standard gitlab runner so any changes you make may break in unexpected ways.
# If you feel for some reason this file MUST be changed, please post on the course forum so it can
# be discussed between you and course staff.
#
image: comp1531/basic:latest

stages:
  - checks

pytest:
  stage: checks
  script:
    - SERVER_LOG=$(mktemp)
    - coverage run -m src.server &> $SERVER_LOG & pid=$!
    - sleep 2
    - ps -o pid | egrep -q "^\s*${pid}$" || (cat $SERVER_LOG && exit 1)
    - pytest tests/
    - kill -SIGINT %1
    - cat $SERVER_LOG
    - coverage report
    - coverage html
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    paths:
      - htmlcov/
    expose_as: Coverage Report
    expire_in: 1 week

pylint:
  stage: checks
  script:
    - find . -type f -name "*.py" | egrep -v ".git/*" | xargs pylint
